= Planned Copy
Ștefan Suciu
0.840, 2016-11-15
:toc:
:imagesdir: assets/images
:homepage: http://stefansuciu.ro

Planned Copy - a smarter copy application for your Linux box.

== Description

This is my solution for the task of managing configuration files,
scripts and other files that need to be copied around.

The idea behind the application is simple, but the implementation is
complicated... :) I keep my configuration files, like many others do,
in a Git repository.  The task is to install this files to the places
where they belong to, as automated as possible and syncronize any
changes.

A small Git repository in `/home/user/configs` looks like this:

....
.
├── emacs
│   ├── custom.el
│   ├── init.el
│   └── resource.yml
├── kde
│   ├── Shell.profile
│   └── resource.yml
├── linux
│   ├── ackrc
│   ├── bash_alias
│   ├── bash_profile
│   ├── bash_prompt
│   ├── bashrc
│   └── resource.yml
└── system
    ├── rc.firebird
    ├── rc.postgresql
    └── resource.yml
....

My solution is to use a configuration file (`resource.yml` is the
default name of the file) in each project directory with the following
minimum information for each item:

destination name:: the name of the file in the destination directory, without the path;
destination path:: the destination absolute path (see issue #19);
destination perm:: the permissions for the destination file (ex: 0644);
source name:: the name of the file in the source repository, without the path;
source path:: the source path relative to the repository directory;

For example an item in the resource file is configured like this:

.resource.yml
....
---
resources:
  -
    destination:
      name: .ackrc
      path: '~/'
      perm: 0644
    source:
      name: ackrc
      path: linux
....


If the file is not installed or the source and the destination are
different, the `plcp install linux` command will copy and rename the
`linux/ackrc` file to `/home/user/.ackrc` and will set the permissions
to `0644`.

Notice that the name of the file in the repository is without the
starting dot, this way the file is not hidden in the repository and
when is installed gets the correct name.

The `resource.yml` configuration file is automatically
generated/updated by the `plcp resource linux` command, but the
destination path is initially undefined and have to be edited manually
for every record.

Starting with `v0.900` the `add` command can be used to add files to
the repository (EXPERIMENTAL FEATURE):

....
$ plcp add /path/to/a/file.txt
or
$ plcp add /path/to/some/configs
....


== Commands

The commands can be abbreviated to the shortest unambiguous name.  The
command examples bellow, show the shortest usable name and the list of
commands show the optional part in square brackets.

The commands:

add::

Add file(s) to a project and update the resource file

....
plcp a <project> ./path/to/a/file  - add the 'file' file

plcp a <project> ./path/           - add a directory recursively

plcp a <project> ./path/*.conf     - add files using wildcards

plcp a <project> file1 file2 file3 - add a list of files (not yet!)
....

ch[eck]::    Compare the repository files with the installed versions
co[nfig]::   Configure the application
d[iff]::     Run a diff utility on the repo files and the installed versions
h[elp]::     Prints this usage information
i[nstall]::  Install the project items (files)
l[ist]::     Print a list of the projects in the repository
rep[o]::     Manage the repository
res[ource]:: Create/update a resource file
s[ync]::     Synchronize the configuration files
v[ersion]::  Print the current version


== Quick Usage

The initial configuration of `plcp`:

....
$ plcp co[nfig] set --url user@host:/path/to/git-repos/configs.git
$ plcp co[nfig] set --path /home/user/configs
....

Clone the repository to localhost:

....
$ plcp rep[o] clone
....

Add/update the `resource.yml` file in the `linux` directory:

....
$ plcp res[ource] linux
....

Edit the `linux/resource.yml` file and set the destination path for
all the items.

Finally install the files with:

....
$ plcp i[nstall] linux
....


== License And Copyright

Copyright (C) 2016 Ștefan Suciu

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 dated June, 1991 or at your option
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

A copy of the GNU General Public License is available in the source tree;
if not, write to the Free Software Foundation, Inc.,
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
