= Planned Copy
Ștefan Suciu
0.911, 2016-12-07
:toc:
:icons: font
:homepage: http://stefansuciu.ro

Planned Copy - a smarter copy application for your Linux box.

== Description

This is my solution for the task of managing configuration files,
scripts and other files that need to be copied around quite often.

The idea behind the application is simple, but the implementation is
quite complicated...

I keep my configuration files, like many others do, in a Git
repository, the goal is to install (copy) this files to the places
where they belong to and synchronize any changes back and forth as
automated and as safe as possible.

A small Git repository in `/home/user/configs` may look like this:

....
.
├── emacs
│   ├── custom.el
│   ├── init.el
│   └── resource.yml
├── kde
│   ├── Shell.profile
│   └── resource.yml
├── user
│   ├── ackrc
│   ├── bash_alias
│   ├── bash_profile
│   ├── bash_prompt
│   ├── bashrc
│   └── resource.yml
└── system
    ├── rc.firebird
    ├── rc.postgresql
    └── resource.yml
....

The solution is to use a configuration file named `resource.yml` by
default, in each project directory with the following minimum
information for each item:

destination name:: the name of the file in the destination directory, without the path;
destination path:: the destination absolute path (see issue #19);
destination perm:: the permissions for the destination file (ex: 0644);
source name:: the name of the file in the source repository, without the path;
source path:: the source path relative to the repository directory;

In the above example resource files there are 4 project directories:
_emacs_, _kde_, _user_ and _system_.

For example a minimal configuration for an item in the resource file
looks like this:

.resource.yml
....
---
resources:
  -
    destination:
      name: .ackrc
      path: '~/'
      perm: 0644
    source:
      name: ackrc
      path: user
....

If the file is not installed or the source and the destination are
different, the `plcp install user` command will copy and rename the
`user/ackrc` file to `/home/<username>/.ackrc` and will set the
permissions to `0644`.  Starting with `v0.910` a backup for the
original file will be created.

NOTE: The name of the file in the repository is without the starting
      dot, this way the file is not hidden in the repository and when
      is installed gets the correct name.

The resource configuration file is automatically generated/updated by
the `plcp resource user` command, but the destination path is
initially undefined and have to be edited manually for every record.

Starting with `v0.911` the `add` command can be used to add files to
the repository (EXPERIMENTAL).


== Configuration

=== Initial Configuration

The configuration file(s) are in the format used by Git and parsed and
modified by the `Config::GitLike` module.  The configuration file
name is `plannedcopyrc` for the system and `.plannedcopyrc` for the
users.

The minimum required configuration contains the path to a clone of the
`configs` repository on localhost.  The name of the repository can be
anything.

IMPORTANT: The application was not tested with paths containing
           spaces, and it may not work properly, so is better to avoid
           them.

....
$ plcp config set --path /home/user/configs
....

Another setting, used only by the `repo` command, is the URL to the
remote repository.  If the local clone of the repository does not
exist, it can be created using the `repo` command.

....
[core]
    #editor = emacs
    diff-tool = kompare
[local]
    path = /home/username/configs/
[remote]
    url = ssh://username@host/path/to/git-repos/configs.git
[resource]
    open_editor = true
[color]
    info  = yellow2
    warn  = blue2
    error = red2
    done  = green2
    none  = clear
....

....
$ plcp config set --url user@host:/path/to/git-repos/configs.git
....


=== Configuration Reference

The sections of the configuration file are:

==== core

The `core` section contains miscellaneous settings.

    editor = emacs

Defaults to the contents of the `EDITOR` environment variable.

    diff-tool = diff

Defaults to `diff` for the root user and to `kompare` for regular users.

    resource-file = resource.yml

==== local

    path = /home/username/configs/

The local path to a clone of the `configs` repository, and must be set
before the first run.

==== remote

    url = ssh://username@host/path/to/git-repos/configs.git

 The URL to the remote repository, is used by the `repo` command and
it's purpose is to make the initial clone of the repository.

WARNING: Not thoroughly tested!

==== resource

    open_editor = true | false

If the value is `true`, the `resource` command opens the resource file
in the editor after it is updated.

==== color

    info  = yellow2
    warn  = blue2
    error = red2
    done  = green2
    none  = clear

The colors are those provided by the `Term::ExtendedColor` module.


== Commands

The commands can be abbreviated to the shortest unambiguous name.  The
command examples bellow, show the shortest usable name and the list of
commands show the optional part in square brackets.


=== Commands Reference

NOTE: The project directory must exist.

a[dd]::      add file(s) to an existing `dir|project` and update the resource file.

....
plcp a <project> </absolute/path>
....

Examples:
....
plcp a <project> ./path/to/a/file  - add the 'file' file

plcp a <project> ./path/           - add a directory recursively

plcp a <project> ./path/*.conf     - add files using wildcards

plcp a <project> file1 file2 file3 - add a list of files (NOT yet!)
....

WARNING: This is an early implementation, and is not thoroughly tested!

ch[eck]::    compare the files from the repository with the installed files.

Examples:
....
plcp ch <project> [file]
....

co[nfig]::   configure the application
d[iff]::     run a diff utility on the repo files and the installed versions
h[elp]::     prints this usage information
i[nstall]::  install the project items (files)
l[ist]::     print a list of the projects in the repository
rep[o]::     manage the repository
res[ource]:: create/update a resource file
se[arch]::   search for a file in the repository
sy[nc]::     synchronize the configuration files
v[ersion]::  print the current version


== Usage

The check command can be used to print the project name with
differences found between the files in the repository and the installed
files.

....
$ plcp ch
Checking ....... .
 user ....................................................................... 1
 kde ........................................................................ 1
 emacs ...................................................................... 1
....

This output means that for every project there is a file that is not
synchronized with the repository.  To find out which, we need to run
the command again with the project parameter:

....
$ plcp ch user

 bash_alias ....................................................... .bash_alias
 bash_prompt .......................................... { undef }/rkhunter.conf

Summary:
 - processed: 17 records
 - skipped  : 1
 - same     : 15
 - different: 1
....

The `undef` in the second line means the the item doesn't have a
destination path defined in the resource file.

If we add the *-v|--verbose* option and run the command again, more
information will be printed for the items with issues, for example,
`Not installed.`, or `Read permission denied: <filename>`.


== License And Copyright

Copyright (C) 2016 Ștefan Suciu

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 dated June, 1991 or at your option
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

A copy of the GNU General Public License is available in the source tree;
if not, write to the Free Software Foundation, Inc.,
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
