use Test::More;

use_ok( 'App::PlannedCopy::Command::Sync' );
use_ok( 'App::PlannedCopy::Command::Install' );
use_ok( 'App::PlannedCopy::Command::Check' );
use_ok( 'App::PlannedCopy::Command::Repo' );
use_ok( 'App::PlannedCopy::Command::Resu' );
use_ok( 'App::PlannedCopy::Command::Config' );
use_ok( 'App::PlannedCopy::Command::List' );
use_ok( 'App::PlannedCopy::Command::Diff' );
use_ok( 'App::PlannedCopy::Types' );
use_ok( 'App::PlannedCopy::Role::Validate::Sync' );
use_ok( 'App::PlannedCopy::Role::Validate::Install' );
use_ok( 'App::PlannedCopy::Role::Validate::Check' );
use_ok( 'App::PlannedCopy::Role::Validate::Common' );
use_ok( 'App::PlannedCopy::Role::Validate::Diff' );
use_ok( 'App::PlannedCopy::Role::Base' );
use_ok( 'App::PlannedCopy::Role::Resource::Element' );
use_ok( 'App::PlannedCopy::Role::Printable' );
use_ok( 'App::PlannedCopy::Role::Utils' );
use_ok( 'App::PlannedCopy::Exceptions' );
use_ok( 'App::PlannedCopy::Config' );
use_ok( 'App::PlannedCopy::Resource::Write' );
use_ok( 'App::PlannedCopy::Resource::Read' );
use_ok( 'App::PlannedCopy::Resource::Element::Source' );
use_ok( 'App::PlannedCopy::Resource::Element::Destination' );
use_ok( 'App::PlannedCopy::Resource::Element' );
use_ok( 'App::PlannedCopy::Resource' );
use_ok( 'App::PlannedCopy::Ls' );
use_ok( 'App::PlannedCopy' );

done_testing;
